### ISSUE TITLE
Adding wildcard or notfound route "*" results in external stylesheets being sent with wrong mimetype

### ISSUE THREAD

**Issue by shankie-codes** [RickWong/react-isomorphic-starterkit#82]
Hi @RickWong and team,

I'm having a bit of a strange issue. I've got an existing working client-only React app that I'm refactoring into the starterkit. Because I have a stylesheet direct from my designer, I prefer to use a stylesheet included using `<link>`, so my template in `server.js` now looks like this:

```
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <title>react-isomorphic-starterkit</title>
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="stylesheet" href="/style.css">
  </head>
```

That's all groovy and works fine until I include a wildcard route in react-router, like so:

```
<Router>
  <Route path="/" component={Main} />
  <Route path="*" component={NotFound} />
</Router>
```

When I add the wildcard, my stylesheet gets transmitted as MIME type plain text, so Chrome goes:

`Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:8000/style.css".`

I think I can probably work around it by loading in a stylesheet using React. I'll try that now, but would still be interesting to know what the cause is.

N.B. these routes are working fine when the app is client-only, so I can only assume that it's something to do with Koa or Transmit.

**Comment by shankie-codes** [comment]
FWIW, I reported the above using `npm run watch`. If you instead switch to production, the contents of `client.js` seem to get replaced with the contents of the template, e.g.:

```
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <title>react-isomorphic-starterkit</title>
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="stylesheet" href="/style.css">
  </head>
  <body>
    <div id="react-root"><div data-reactid=".11sc4xih9fk" data-react-checksum="534975139">I&#x27;m not found</div></div>
  <script>window.__reactTransmitPacket=[]</script><script src="/dist/client.js"></script></body>
</html>
```

...which of course makes the browser go loopy, because that's HTML, not JS.

Interesting that it does seem to render the contents of the `NotFound` component into the `react-root` when this happens. Hmm.

**Comment by shankie-codes** [comment]
A wee bit more info (again, hope it's helpful!)... this also causes other static assets (referenced relatively inside the `static` folder) to fail to load. They don't seem to have the luxury of errors like that stylesheet does (and oddly, they do get code `200`) back, but they don't load, all the same.

**Comment by shankie-codes** [comment]
And even more info...! This (or similar things) seem to happen every time I put a pattern-matched route into the `{routes}` object, e.g.

`<Route path=":category" component={Category}>`

**Comment by shankie-codes** [comment]
It's been an afternoon of experimentation here! I've now downgraded from Koa to Hapi and it all seems... happy.

I'll leave it to you now Rick! Koa looks promising. Happy to help with testing once you have an idea what's going on.

**Comment by RickWong** [comment]
Thanks a lot @shankiesan. I'll look into it soon.

**Comment by RickWong** [comment]
I couldn't reproduce this in the latest versions. Can this bug be closed?

**Comment by shankie-codes** [comment]
I haven't tested later versions, but if you can add a wildcard route and still load static assets, then I'd say it's ok to be closed (sorry, don't have time to test at the moment).

I guess there was something weird with Koa?

**Comment by Jimtattersall** [comment]
FYI - this is probably down to line 21 in server.js
`
app.use(koaStatic("static", {defer: true}));
`

When set to true the static resource is interpreted after the router. As such if a route is matched in routes.js the static asset won't be rendered. 

Changing line 21 of server.js to 
`app.use(koaStatic("static"));`

will ensure the static resources are tried first and should resolve the issue you are having.

**Comment by RickWong** [comment]
Thanks @Jimtattersall, I'll change it.

**Comment by Jimtattersall** [comment]
@RickWong a pleasure. And thank you for creating and maintaining such an invaluable project.

**Comment by shankie-codes** [comment]
I would have never thought of that @Jimtattersall . Cheers!

**Comment by globexdesigns** [comment]
Unfortunately this is still an issue for me with the latest version and using `app.use(koaStatic("static"));`. Everything from /static is being served as a 404 HTML page instead of serving the static file.
